---
# tasks file for ansible-chrony
- name: Install Chrony
  package:
    name: chrony
    state: present
  become: true

- include: config_chrony.yml
  tags:
    - ansible_chrony
    - ansible_chrony_config
